/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package electricitynew;
import static electricitynew.myvariables.password;
import static electricitynew.myvariables.path;
import static electricitynew.myvariables.place;
import static electricitynew.myvariables.username;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author parveen
 */
public class modifyconnection extends javax.swing.JInternalFrame {

    /**
     * Creates new form modifyconnection
     */
    public modifyconnection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modify Connection");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Connection No", "Name", "Phone", "Address", "District", "Date", "Gender"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Connection Id");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");

        jButton3.setText("Search by Id");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jButton4.setText("Search by Name");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jButton1)
                                .addGap(67, 67, 67)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(jTextField2))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(177, 177, 177))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
    Connection myconnection;
    myconnection=DriverManager.getConnection(path+place, username, password);
try{
    String q="update createconnection set pname=?,pfname=?,pmname=?,choosedistrict=?,Mno=?,address=?,date=?,gender=? where cid=?";
    PreparedStatement mysat=myconnection.prepareStatement(q); 
        ResultSet myresult=mysat.executeQuery();

     if(myresult.next())
            { 
   DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
    do
    {
        String cno,name,ph,add,dist,gen,da;
        cno=myresult.getString("cid");
        name=myresult.getString("pname");
        ph=myresult.getString("Mno");
        add=myresult.getString("address");
        dist=myresult.getString("choosedistrict");
        da=myresult.getString("date");
        gen=myresult.getString("gender");
        mymodel.addRow(new Object[]{cno,name,ph,add,dist,da,gen});
   
            mysat.setString(1, cno);
            mysat.setString(2,name);
            mysat.setString(3, ph);
            mysat.setString(4, add);
            mysat.setString(5, dist);
            mysat.setString(6, da);
            mysat.setString(7, gen);     
 }while(myresult.next());
    mysat.executeQuery();
    
            }
    JOptionPane.showInternalMessageDialog(rootPane, " Updated Sucessfully ", "Sucess", JOptionPane.YES_NO_CANCEL_OPTION);
}
catch(Exception  e)
{
e.printStackTrace();
JOptionPane.showMessageDialog(rootPane,"Error ocuure due to "+e.getMessage(),"Error",   JOptionPane.ERROR_MESSAGE);
    }                                        
finally
{
        try {
            myconnection.close();
        } catch (SQLException ex) {
        }
}
}       catch (Exception ex) {
    JOptionPane.showMessageDialog(rootPane,"Error ocuure due to "+ex.getMessage());

        }
        









// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try 
{
    Connection myconnection;
  
    myconnection=DriverManager.getConnection(path+place, username, password);
try{
    String q="select *  from createconnection where cid=?";
    PreparedStatement mysat=myconnection.prepareStatement(q);
       mysat.setString(1,jTextField1.getText());
    ResultSet myresult=mysat.executeQuery();
    if(myresult.next())
            { 
   DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
    do
    {
        String cno,name,ph,add,dist,gen,da;
        cno=myresult.getString("cid");
        name=myresult.getString("pname");
        ph=myresult.getString("Mno");
        add=myresult.getString("address");
        dist=myresult.getString("choosedistrict");
        da=myresult.getString("date");
        gen=myresult.getString("gender");
        mymodel.addRow(new Object[]{cno,name,ph,add,dist,da,gen});
    }
    while(myresult.next());
        mysat.executeQuery();
  
            }
    else
    {
         JOptionPane.showMessageDialog(rootPane, "enterted wrong input");
    } 

    
}
catch(Exception  e)
{
e.printStackTrace();
JOptionPane.showMessageDialog(rootPane,"Error ocuure due to "+e.getMessage(),"Error",   JOptionPane.ERROR_MESSAGE);
    }                                        
  finally
{
    myconnection.close();
}
}
catch(Exception e)
        {
        e.printStackTrace();
        JOptionPane.showMessageDialog(rootPane, "Error in connection due to"+e.getMessage() );
        } 


// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  try 
{
    Connection myconnection;
  
    myconnection=DriverManager.getConnection(path+place, username, password);
try{
    String q="select * from createconnection where pname like '%"+ jTextField2.getText() +"%'" ;
    PreparedStatement mysat=myconnection.prepareStatement(q);
 
    ResultSet myresult=mysat.executeQuery();
    
    if(myresult.next())
{
    DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
    mymodel.setRowCount(0);
    do
    {
        String cno,name,ph,add,dist,da,gen;
        cno=myresult.getString("cid");
        name=myresult.getString("pname");
        dist=myresult.getString("choosedistrict");
        ph=myresult.getString("Mno");
        add=myresult.getString("address");
        da=myresult.getString("date");
        gen=myresult.getString("gender");
        mymodel.addRow(new Object[]{cno,name,ph,add,dist,da,gen});
    }
    while(myresult.next());

}
 else           
    {
        JOptionPane.showInternalMessageDialog(rootPane, "No connections found ", " ", JOptionPane.YES_NO_CANCEL_OPTION);

}

}
catch(Exception  e)
{
e.printStackTrace();
JOptionPane.showMessageDialog(rootPane,"Error ocuure due to "+e.getMessage(),"Error",   JOptionPane.ERROR_MESSAGE);
    }                                        
  finally
{
   
    myconnection.close();
}
}
catch(Exception e)
        {
        e.printStackTrace();
        JOptionPane.showMessageDialog(rootPane, "Error in connection due to"+e.getMessage() );
        }   
        
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
